version: '3.1'
services:
  app:
    container_name: studujdopravu
    restart: always
    build: .
    ports:
      - '80:3000'
    env_file: ./.env
    links:
      - mariadb
  mariadb:
    env_file: ./.env
    container_name: mariadb
    image: mariadb:bionic
    restart: always
    ports:
      - '3306:3306'
    environment:
      "MYSQL_USER": "${DB_USER}"
      "MYSQL_PASSWORD": "${DB_PASSWORD}"
      "MYSQL_DATABASE": "${DB_NAME}"
      "MYSQL_ROOT_PASSWORD": "${DB_ROOT_PASSWORD}"

